### ISSUE TITLE
路线建议

### ISSUE THREAD

**Issue by Amecy** [wofeiwo/alfred-amap#1]
插件挺好用的，就是A2B的功能有点麻烦，希望改进，给出两种建议方案：
> 西二旗 到 望京：
1. amap 西二旗 望京
2. amap 西二旗 to 望京

**Comment by wofeiwo** [comment]
抱歉才看到这个issue。
实际上我调用的是高德地图的搜索机制，因此，在高德地图的语义分析中，“A到B”和“A去B”是有意义的，暂时没法识别“A B”或者“AtoB”的形式。当然，我可以预先做一些字符处理替代。但是当前的模式已经足够使用且够方便了（多打一个字）。因此暂时不做此feature

**Comment by wofeiwo** [comment]
哦，更正一下，之前百度地图是有“A到B”和“A去B”的语义。
高德版本的待我有时间研究一下。

**Comment by thatscode** [comment]
amap的路线查询好像不能正常使用，bmap的是可用的。

debug报错如下，python版本的问题?：
```
[2019-02-11 17:38:05][input.scriptfilter] Queuing argument '西二旗到望京'
[2019-02-11 17:38:06][input.scriptfilter] Script with argument '(null)' finished
[2019-02-11 17:38:06][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "amap.py", line 64, in <module>
    main(sys.argv)
  File "amap.py", line 60, in main
    print(feeds)
  File "/Users/stephen/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.87911060-62B2-4F42-BA65-9119F686EF76/feedback.py", line 26, in __repr__
    return et.tostring(self.feedback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
```

**Comment by wofeiwo** [comment]
@thatscode 单独起了一个issue处理吧。看起来应该是文件编码问题，我有空的时候看一下

**Comment by lolstudio** [comment]
> @thatscode 单独起了一个issue处理吧。看起来应该是文件编码问题，我有空的时候看一下

挖坟求更新。。😂
